<?php
/** @var \Begin\Practice\Block\Student\Create $block */
$url = $block->getActionForm();
?>
<form action="<?= $url ?>" method="POST">
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Name') ?>:</label>
        <input type="text" name="name" placeholder="Enter Name"/>
    </div>
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Gender') ?>:</label>
        <select name="gender">
            <option value="" selected hidden="">Select Gender:</option>
            <option value="1">Male</option>
            <option value="0">Female</option>
            <option value="3">Other</option>
        </select>
    </div>
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Date of Birth') ?>:</label>
        <input type="date" name="dob" placeholder="Enter Birth"/>
    </div>
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Address') ?>:</label>
        <input type="text" name="address" placeholder="Enter Address"/>
    </div>
    <button type="submit"><?= __('Save') ?></button>
</form>
