<?php
/** @var \Begin\Practice\Block\Student\Edit $block */
$student = $block->getStudent();
?>
<form action="<?= $block->getActionForm($student->getId()) ?>" method="POST">
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Name') ?>:</label>
        <input type="text" name="name" placeholder="Enter Name" value="<?= $student->getName() ?>"/>
    </div>
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Gender') ?>:</label>
        <select name="gender">
            <option value="" selected hidden="">Select Gender:</option>
            <option value="1" <?= $student->getGender() == 1 ? 'selected': '' ?>>Male</option>
            <option value="0" <?= $student->getGender() == 0 ? 'selected': '' ?>>Female</option>
            <option value="3" <?= $student->getGender() == 3 ? 'selected': '' ?>>Other</option>
        </select>
    </div>
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Date of Birth') ?>:</label>
        <input type="date" name="dob" placeholder="Enter Birth" value="<?= $student->getDob() ?>"/>
    </div>
    <div class="form-row">
        <label for="entity-id-filter"><?php echo __('Address') ?>:</label>
        <input type="text" name="address" placeholder="Enter Address" value="<?= $student->getAddress() ?>"/>
    </div>
    <button type="submit"><?= __('Save') ?></button>
</form>
